title: chaofanchen
description: chaofanchen
name_pinyin: Chaofan CHEN 
name_chinese: 陈超凡
theme: jekyll-theme-dinky
email: chencf@mail.ustc.edu.cn
email_full: mailto:chencf@mail.ustc.edu.cn


aff1: Institute of Automation, Chinese Academy of Sciences (CASIA),
aff1url: http://www.ia.cas.cn/
aff2: University of Science and Technology of China (USTC),
aff2url: https://www.ustc.edu.cn/
