title: Chaofan CHEN
description: Chaofan CHEN
name_pinyin: Chaofan CHEN 
name_chinese: 陈超凡
theme: jekyll-theme-dinky
email: chencfbupt@gmail.com


aff1: Beijing University of Technology (北京工业大学)
aff1url: https://cst.bjut.edu.cn/index.htm

